version: "3.7"
services:
    igw:
        build:
            context: ../
            dockerfile: Dockerfile
        image: local-igw-integration-tests-build
        container_name: igw
        ports:
            - "10000:10000"
        networks:
            - igw
        environment:
            APPLICATION_HOST: httpbin
            APPLICATION_PORT: 80
        healthcheck:
            test: [ "CMD", "wget", "http://localhost:10000/nginx-health" ]
            interval: 1s
            timeout: 1s
            retries: 2
            start_period: 2s
        depends_on:
            -   httpbin

    httpbin:
        image: kennethreitz/httpbin
        container_name: httpbin
        networks:
            - igw

networks:
    igw:
        name: igw


